services:
  worker-dev:
    build: 
      dockerfile: Dockerfile.dev
      args:
        BUILD_VERSION: dev-compose
    ports:
      - "8080:8080"
    environment:
      - DATABASE_PATH=/data/llm-proxy.db
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - JWT_SECRET=dev-jwt-secret-key
      - INTERNAL_API_KEY=dev-internal-key
      - RATE_LIMIT_REQUESTS=1000
      - RATE_LIMIT_WINDOW=60
      - BUILD_VERSION=dev-compose
    volumes:
      - .:/app
      - worker_dev_data:/data
    networks:
      - llm-proxy-network

volumes:
  worker_dev_data:

networks:
  llm-proxy-network:
    driver: bridge
